# Generated by Django 3.1.7 on 2021-03-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20210329_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pro',
        ),
    ]
